language: shell
os: linux
services: docker

branches:
  only:
    - feature/travis

branches:
  except:
    - /^release-/

cache:
  directories:
    - out/archive

matrix:
  include:
    # Userland
    - stage: build
      script:
        - ls out/archive
        - bash ./build -u

    # LinuxKit variants
    - &build-kernel
      script:
        - ls out/archive
        - bash ./build -k $KERNEL
      env: KERNEL=4.9.184-linuxkit
    - <<: *build-kernel
      env: KERNEL=4.9.125-linuxkit

    # Ubuntu variants
    - <<: *build-kernel
      env: KERNEL=5.0.0-25-generic
    - <<: *build-kernel
      env: KERNEL=4.15.0-1034-gcp
    - <<: *build-kernel
      env: KERNEL=4.15.0-1044-aws

    # CentOS variants
    - <<: *build-kernel
      env: KERNEL=3.10.0-957.1.3.el7.x86_64

    # Deploy stage
    - stage: deploy
      before_deploy:
        - ls out/archive
        - git config --local user.name "Eric Schrock"
        - git config --local user.email "Eric.Schrock@delphix.com"
        - export TRAVIS_TAG=${TRAVIS_TAG:-release-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file_glob: true
        file: out/archive/*
        on:
          branch: feature/travis
