language: shell
os: linux
services: docker

branches:
  only:
    - feature/travis
    - /^untagged/

cache:
  directories:
    - out/archive

env:
  - TARGET=5.0.0-25-generic
  - TARGET=4.9.125-linuxkit
script:
  - bash ./build $TARGET

matrix:
  include:
    - stage: deploy
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file: out/archive/*
        file_glob: true
        on:
          branch: feature/travis
