language: shell
os: linux
services: docker

branches:
  only:
    - master

env:
  # Userland build
  - MODE=-u KERNEL=4.9.184-linuxkit
  # LinuxKit variants
  - MODE=-k KERNEL=4.9.184-linuxkit
  - MODE=-k KERNEL=4.9.125-linuxkit
  # Ubuntu variants
  - MODE=-k KERNEL=5.0.0-25-generic
  - MODE=-k KERNEL=4.15.0-1040-gcp
  - MODE=-k KERNEL=4.15.0-1034-gcp
  - MODE=-k KERNEL=4.15.0-1044-aws
  # CentOS variants
  - MODE=-k KERNEL=3.10.0-957.1.3.el7.x86_64

script:
  - bash ./build -b $S3_URL $MODE $KERNEL

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  upload-dir: $S3_FOLDER
  skip_cleanup: true
  local_dir: out/archive
  on:
    branch: master
