language: shell
os: linux
services: docker

branches:
  only:
    - feature/travis

env:
  # Userland build
  - MODE=-u KERNEL=4.9.184-linuxkit

script:
  - bash ./build -b $S3_URL $MODE $KERNEL

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  upload-dir: $S3_FOLDER
  skip_cleanup: true
  local_dir: out/archive
  on:
    branch: feature/travis
