language: generic
services:
  - docker
branches:
  only:
    - feature/travis
    - /^untagged/
jobs:
  include:
    - stage: test
      script:
        - bash ./build 5.0.0-25-generic
    - stage: deploy
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file: out/archive/*
        file_glob: true
        on:
          branch: feature/travis
