language: shell
os: linux
services: docker

branches:
  only:
    - feature/travis
    - /^untagged/

cache:
  directories:
    - out/archive

env:
  - TARGET=5.0.0-25-generic
  - TARGET=4.9.125-linuxkit
script:
  - bash ./build $TARGET

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  file: out/archive/*
  skip_cleanup: true
  on:
    branch: feature/travis
