name: Manual Kernel Check

on:
  workflow_dispatch:
    inputs:
      ubuntu:
        description: "ubuntu version"
        required: true
        default: "22.04"
      zfs:
        description: "zfs version"
        required: true
        default: "2.1.5"
      kernel:
        description: "linux kernel"
        required: true

jobs:
  build_kernel_ubuntu-manual:
    name: Build Kernel
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Create Kernel Build File
        run: ./scripts/setup_kernel.sh
      - name: Output Build File
        run: cat src/$(uname -r)/uname
      - name: Build
        run: make manual S3=${{ secrets.s3_url }} ZFS=${{ github.event.inputs.zfs }} KERNEL=${{ github.event.inputs.kernel }} OS=${{ github.event.inputs.ubuntu }}
      - name: Publish
        run: docker run -e "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -e "AWS_DEFAULT_REGION=us-west-2" zfs-builder /publish ${{ secrets.s3_bucket }}