name: Nightly Kernel Check

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build_userland:
    name: Build Userland
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        zfs:
          - 0.8.2
          - 2.0.4
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ./build -b ${{ secrets.s3_url }} -z ${{ matrix.zfs }} 4.9.184-linuxkit
      - name: Publish
        run: ./publish ${{ secrets.s3_bucket }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build_kernel:
    name: Build Kernel
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        zfs:
          - 0.8.2
          - 2.0.4
        kernels:
          - 5.4.0-1063-azure
          - 5.4.0-1064-azure
    steps:
      - uses: actions/checkout@v1
      - name: Create Kernel Build File
        run: ./scripts/setup_kernel.sh
      - name: Output Build File
        run: cat src/$(uname -r)/uname
      - name: Build
        run: ./build_local.sh -b ${{ secrets.s3_url }} -k -z ${{ matrix.zfs }} -d $GITHUB_WORKSPACE -r ${{ matrix.kernels }}
        env:
          ZFS_VERSION: zfs-${{ matrix.zfs }}
      - name: Publish
        run: ./publish ${{ secrets.s3_bucket }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
