name: Push

on: push

jobs:
  build_userland:
    name: Build Userland
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        zfs:
          - 0.8.2
          - 2.0.4
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ./build -b ${{ secrets.s3_url }} -z ${{ matrix.zfs }} 4.9.184-linuxkit
      - name: Publish
        run: ./publish ${{ secrets.s3_bucket }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  build_kernel:
    name: Build Kernel
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        zfs:
          - 0.8.2
          - 2.0.4
        kernel:
          # Ubuntu variants
          - 5.11.0-1022-aws
          - 5.13.0-28-generic
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ./build -b ${{ secrets.s3_url }} -k -z ${{ matrix.zfs }} ${{ matrix.kernel }}
      - name: Publish
        run: ./publish ${{ secrets.s3_bucket }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
