#
name: Push

on: push

jobs:
  build:
    name: Build
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        zfs: [ "0.8.1" ]
        mode :
          # Userland build
          - MODE=-u KERNEL=4.9.184-linuxkit
          # LinuxKit variants
          - MODE=-k KERNEL=4.9.184-linuxkit
          - MODE=-k KERNEL=4.9.125-linuxkit
          # Ubuntu variants
          - MODE=-k KERNEL=5.0.0-25-generic
          - MODE=-k KERNEL=5.0.0-1016-azure
          - MODE=-k KERNEL=5.0.0-1020-azure
          - MODE=-k KERNEL=4.15.0-1040-gcp
          - MODE=-k KERNEL=4.15.0-1034-gcp
          - MODE=-k KERNEL=4.15.0-1044-aws
          # CentOS variants
          - MODE=-k KERNEL=3.10.0-957.1.3.el7.x86_64
          - MODE=-k KERNEL=3.10.0-957.27.2.el7.x86_64
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ./build -b ${{ secrets.s3_url }} ${{ matrix.mode }}
      - name: Publish
        run: ./publish ${{ secrets.s3_bucket }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
