name: Test

on: push

jobs:
  install_titan:
    name: Install Titan
    runs-on: ubuntu-18.04
    steps:
      - name: Download Titan
        run: curl -Ls https://github.com/titan-data/titan/releases/download/0.5.3/titan-cli-0.5.3-linux_amd64.tar -o titan.tar
      - name: Unpack Titan
        run: tar -xvf titan.tar
      - name: Alias Titan
        run: cp $PWD/titan /usr/local/bin/titan
      - name: Install Titan
        run: titan install
      - name: Docker PS
        run: docker ps
        
      - name: Dump docker logs
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: './logs'
      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz

      - name: Test Clone
        run: titan clone -n hello-world s3web://demo.titan-data.io/hello-world/postgres